### ISSUE TITLE
PDF: Ensure correct layout of IEC Technical Report cover pages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iec#153]
* https://webstore.iec.ch/preview/info_isoiectr30167%7Bed1.0%7Den.pdf
* https://cdn.standards.iteh.ai/samples/104181/d8a747bb14fb411bbf7fc6b8fbea946f/ISO-IEC-TR-63306-1-2020.pdf

**Comment by Intelligent2013** [comment]
Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198075814-fa9729c4-3b38-45f7-bcd0-e09109b20de3.png)

Resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/198075866-6c878ee1-8c6c-4569-96e7-9e59b53c529b.png)

- [ ] only IEC logo
- [ ] `R` sign after logo
- [ ] redundant `/` between `IEC` and `TR` (https://github.com/metanorma/metanorma-iso/issues/657)
- [ ] Edition number - `ED 1` 

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198076507-8af2b26c-d93c-411a-941b-4e0284ab3bb6.png)

Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198076552-ab326db2-57da-441c-abb8-9b3ff67bd7ad.png)

- [ ] - long dash between titles

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198076753-afa6da4e-38f3-4f5d-941f-2136052ff862.png)


Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198076796-e7de3b26-edf3-4ef9-badc-95c5170d4a7d.png)

- [ ] no `ISBN` title

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198076992-9c19d2ee-ff94-4523-a11a-2885b4d7c78d.png)


Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198077051-101f728c-a467-4fe7-970f-a6dbfd4c58bd.png)

- [ ] `ED 1` instead of `:2021`
- [ ] `ISO` only, no `IEC`


Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198077430-c2cecc4d-5588-4291-b4f9-ab7ff10430c6.png)

Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198077487-8154bf04-55a2-4a65-943e-2c82cb117ab6.png)


- [ ] remove `INTERNATIONAL ELECTROTECHNICAL COMMISSION`
- [ ] `IOT` instead of `IoT`

**Comment by Intelligent2013** [comment]
Original PDF:
- [ ] vertically oriented text on the cover page:
![image](https://user-images.githubusercontent.com/5559926/198082269-5d04d281-4b3b-4178-9c21-35ad4fafbbbb.png)


Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198082628-e31ca857-eff3-4f0a-a90c-62c54e9f71a4.png)

Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198082671-87fac1b7-cfe0-44e2-8681-79d4925d442c.png)


- [ ] no `Copyright` before copyright
- [ ] `2020 ISO/IEC` vs. `ISO/IEC 2020`
- [ ] `Geneva, Switzerland` vs. `Published in Switzerland`
- [ ] differences in copyright text
- [ ] `Switzerland` on the new line
- [ ] no 'Fax'
- [ ] links in blue

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198083414-b9a2f55c-fd0b-4d4d-95f1-7f8b4858eb77.png)

Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198083440-b887cb36-64c2-4bbf-a9f7-7b20177561d1.png)

- [ ] ICS delimited by semicolon


Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198083593-2c34c4e2-fbf5-4dcf-9b94-9cc52aef734f.png)


Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198083649-c5e4834a-26c1-4214-91ad-5f4aa2e0e813.png)

- header on two lines


Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198083939-f4c80529-fded-4631-a00b-8c508864d54b.png)

- [ ] double `-` in the title

**Comment by Intelligent2013** [comment]
- [ ] ToC page should starts on page `2` , not `4`

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/198264870-46fd25a4-51d2-41dd-8dd0-d6272406dc67.png)

Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/198264903-d5605d3b-32cb-4a98-9d9b-c82a322adfad.png)

**Comment by Intelligent2013** [comment]
@ronaldtse I don't figure out how to achieve this via XSLT on-fly:
- on the cover pdf, the title renders 'as is':
![image](https://user-images.githubusercontent.com/5559926/198328181-2559a60e-c43b-44ad-961c-3ea9deb1023a.png)

- before preface and main sections, the title renders in upper-cased, but except acronym `IoT`:
![image](https://user-images.githubusercontent.com/5559926/198328266-3ae5aecf-0708-443d-b3c9-2f81bc5fb966.png)

I see two options:
- add an additional document attribute (similar to BIPM's `:title-cover-en:` https://www.metanorma.org/author/bipm/ref/document-attributes/)
- add text formatting style like `Internet of things (%IoT%)`. `%text%` means 'reset any applied style' (`%` just for example, I don't sure at all that it allowed). In NISO STS XML there is the element `roman` for this purpose (https://github.com/metanorma/mnconvert/issues/222)

**Comment by Intelligent2013** [comment]
We have 'CSS declarations' (https://www.metanorma.org/author/topics/document-format/text/#css-declarations). May be this solves it. I'll try it.

**Comment by ronaldtse** [comment]
@Intelligent2013 I think the "roman" tag is probably most applicable, let's move that to a separate issue.

**Comment by Intelligent2013** [comment]
All issues in IEC XSLT updated, except these:
- [ ] redundant `/` between `IEC` and `TR` (https://github.com/metanorma/metanorma-iso/issues/657)
- [ ] Edition number - `ED 1` (https://github.com/metanorma/metanorma-iec/issues/154)
- [ ] IOT instead of IoT (https://github.com/metanorma/metanorma-iec/issues/157)
- [ ] vertically oriented text on the cover page (https://github.com/metanorma/metanorma-iec/issues/154#issuecomment-1293529763):

On hold.

**Comment by Intelligent2013** [comment]
> - [ ] redundant `/` between `IEC` and `TR`

Fixed:
![image](https://github.com/metanorma/metanorma-iec/assets/5559926/643cdf78-37dd-48fe-a367-9c9e5ee650ea)

**Comment by Intelligent2013** [comment]
- [ ]  IOT instead of IoT
Fixed:
![image](https://github.com/metanorma/metanorma-iec/assets/5559926/918aaa7e-0c36-48c8-92b2-04f793d44e25)
